void main(){
  Future ((){
    throw Exception('Algo sali√≥ mal');
  }).then((_){
    print('Exitoooo!!');
  }).catchError((error){
    print('Error : $error');
  });
}